USE [Vitinerario]
GO

/****** Object:  Table [dbo].[APIToken]    Script Date: 10/04/2024 16:57:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APIToken](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DataCreation] [datetime] NOT NULL,
	[Token] [nvarchar](max) NOT NULL,
	[Platform] [nvarchar](50) NULL,
	[DataExpiration] [datetime] NOT NULL,
 CONSTRAINT [PK_APIToken] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


